import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";

/**
 * Shares a PDF file generated by expo-print.
 *
 * expo-print's printToFileAsync returns a URI in a private directory that
 * Sharing.shareAsync cannot always read directly. This copies the file into
 * the app's cache directory with a proper filename before sharing.
 */
export async function sharePdf(uri: string, filename: string) {
  const cacheDir = FileSystem.cacheDirectory;
  if (!cacheDir) {
    // Fallback: try sharing the original URI
    await Sharing.shareAsync(uri, { mimeType: "application/pdf" });
    return;
  }

  const safeName = filename.replace(/[^a-zA-Z0-9_-]/g, "_");
  const dest = `${cacheDir}${safeName}.pdf`;

  try {
    await FileSystem.copyAsync({ from: uri, to: dest });
    await Sharing.shareAsync(dest, { mimeType: "application/pdf" });
  } catch (err) {
    console.error("[PDFShare] Copy/share failed:", err);
    // Fallback: try sharing the original URI
    await Sharing.shareAsync(uri, { mimeType: "application/pdf" });
  }
}
